Updating action flow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -99,9 +99,15 @@ jobs:
       uses: github/codeql-action/upload-sarif@v1
       with:
         sarif_file: codeguru-results.sarif.json
-
+    - name: Check for critical volnurability
+    - run: |
+        CNT=$(cat ./codeguru-results.sarif.json |jq '.[] | select(.severity=="Critical")|.severity' | wc -l)
+        if (( $CNT > 0 )); then
+          echo "Critical findings discovered. Failing."
+          exit 1
+        fi
   deploy:
-    needs: build
+    needs: codescan
     runs-on: ubuntu-latest
     environment: Dev
     permissions:
